<?php

namespace Container9bYaWMI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FLoECBZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FLoECBZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'service' => ['privates', 'App\\Service\\TransactionService', 'getTransactionServiceService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'em' => '?',
            'service' => 'App\\Service\\TransactionService',
            'validator' => '?',
        ]);

        if (isset($container->privates['.service_locator.FLoECBZ'])) {
            return $container->privates['.service_locator.FLoECBZ'];
        }

        return $container->privates['.service_locator.FLoECBZ'] = $instance;
    }
}
