<?php

namespace Container9bYaWMI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GvcmIJJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gvcmIJJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'captchaService' => ['privates', 'App\\Service\\HCaptchaService', 'getHCaptchaServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'captchaService' => 'App\\Service\\HCaptchaService',
            'em' => '?',
            'emailService' => 'App\\Service\\EmailService',
            'passwordHasher' => '?',
        ]);

        if (isset($container->privates['.service_locator.gvcmIJJ'])) {
            return $container->privates['.service_locator.gvcmIJJ'];
        }

        return $container->privates['.service_locator.gvcmIJJ'] = $instance;
    }
}
