<?php

namespace Container9bYaWMI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TransactionService' shared autowired service.
     *
     * @return \App\Service\TransactionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TransactionService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\TransactionService'])) {
            return $container->privates['App\\Service\\TransactionService'];
        }

        $instance = new \App\Service\TransactionService($a);

        if (isset($container->privates['App\\Service\\TransactionService'])) {
            return $container->privates['App\\Service\\TransactionService'];
        }

        return $container->privates['App\\Service\\TransactionService'] = $instance;
    }
}
