<?php

namespace App\Tests\Unit\Entity;

use App\Entity\Compte;
use App\Entity\Utilisateur;
use App\Enum\TypeCompte;
use PHPUnit\Framework\TestCase;

class CompteTest extends TestCase
{
    private Compte $compte;

    protected function setUp(): void
    {
        $this->compte = new Compte();
    }

    /**
     * Regle metier 1 : Creation d'un compte bancaire complet
     */
    public function testCompteCreation(): void
    {
        $utilisateur = new Utilisateur();

        $this->compte->setUtilisateur($utilisateur);
        $this->compte->setNumeroCompte('UNI-2025-001234');
        $this->compte->setSolde('5000.00');
        $this->compte->setTypeCompte(TypeCompte::COURANT);

        $this->assertSame($utilisateur, $this->compte->getUtilisateur());
        $this->assertEquals('UNI-2025-001234', $this->compte->getNumeroCompte());
        $this->assertEquals('5000.00', $this->compte->getSolde());
        $this->assertSame(TypeCompte::COURANT, $this->compte->getTypeCompte());
    }

    /**
     * Regle metier 2 : Le solde initial est 0.00
     */
    public function testDefaultSoldeIsZero(): void
    {
        $this->assertEquals('0.00', $this->compte->getSolde());
    }

    /**
     * Regle metier 3 : Le type de compte par defaut est COURANT
     */
    public function testDefaultTypeIsCourant(): void
    {
        $this->assertSame(TypeCompte::COURANT, $this->compte->getTypeCompte());
    }

    /**
     * Regle metier 4 : Le compte est actif par defaut a la creation
     */
    public function testDefaultEstActifIsTrue(): void
    {
        $this->assertTrue($this->compte->isEstActif());
    }

    /**
     * Regle metier 5 : La date de creation est generee automatiquement
     */
    public function testDateCreationAutoGenerated(): void
    {
        $this->assertInstanceOf(\DateTimeInterface::class, $this->compte->getDateCreation());
    }

    /**
     * Regle metier 6 : Changement de type de compte (COURANT vers EPARGNE)
     */
    public function testChangeTypeCompte(): void
    {
        $this->compte->setTypeCompte(TypeCompte::COURANT);
        $this->assertSame(TypeCompte::COURANT, $this->compte->getTypeCompte());

        $this->compte->setTypeCompte(TypeCompte::EPARGNE);
        $this->assertSame(TypeCompte::EPARGNE, $this->compte->getTypeCompte());
    }

    /**
     * Regle metier 7 : Desactivation d'un compte
     */
    public function testDesactiverCompte(): void
    {
        $this->assertTrue($this->compte->isEstActif());

        $this->compte->setEstActif(false);
        $this->assertFalse($this->compte->isEstActif());
    }

    /**
     * Regle metier 8 : Un compte est associe a un utilisateur obligatoirement
     */
    public function testCompteRequiresUtilisateur(): void
    {
        $this->assertNull($this->compte->getUtilisateur());

        $utilisateur = new Utilisateur();
        $this->compte->setUtilisateur($utilisateur);
        $this->assertSame($utilisateur, $this->compte->getUtilisateur());
    }

    /**
     * Regle metier 9 : Mise a jour du solde apres depot
     */
    public function testUpdateSoldeAfterDepot(): void
    {
        $this->compte->setSolde('1000.00');
        $soldeInitial = (float) $this->compte->getSolde();
        $montantDepot = 500.00;
        $nouveauSolde = number_format($soldeInitial + $montantDepot, 2, '.', '');
        $this->compte->setSolde($nouveauSolde);

        $this->assertEquals('1500.00', $this->compte->getSolde());
    }

    /**
     * Regle metier 10 : Mise a jour du solde apres retrait
     */
    public function testUpdateSoldeAfterRetrait(): void
    {
        $this->compte->setSolde('2000.00');
        $soldeInitial = (float) $this->compte->getSolde();
        $montantRetrait = 750.00;
        $nouveauSolde = number_format($soldeInitial - $montantRetrait, 2, '.', '');
        $this->compte->setSolde($nouveauSolde);

        $this->assertEquals('1250.00', $this->compte->getSolde());
    }
}
