<?php

namespace App\Tests\Unit\Entity;

use App\Entity\HistoriqueConnexion;
use App\Entity\Utilisateur;
use PHPUnit\Framework\TestCase;

class HistoriqueConnexionTest extends TestCase
{
    private HistoriqueConnexion $historique;

    protected function setUp(): void
    {
        $this->historique = new HistoriqueConnexion();
    }

    /**
     * Regle metier 1 : Enregistrement complet d'une connexion
     */
    public function testHistoriqueCreation(): void
    {
        $utilisateur = new Utilisateur();

        $this->historique->setUtilisateur($utilisateur);
        $this->historique->setIpAddress('192.168.1.1');
        $this->historique->setDeviceInfo('iPhone 15 Pro');
        $this->historique->setBrowserInfo('Safari 17.0');

        $this->assertSame($utilisateur, $this->historique->getUtilisateur());
        $this->assertEquals('192.168.1.1', $this->historique->getIpAddress());
        $this->assertEquals('iPhone 15 Pro', $this->historique->getDeviceInfo());
        $this->assertEquals('Safari 17.0', $this->historique->getBrowserInfo());
    }

    /**
     * Regle metier 2 : Le statut par defaut est SUCCESS
     */
    public function testDefaultStatutIsSuccess(): void
    {
        $this->assertEquals('SUCCESS', $this->historique->getStatut());
    }

    /**
     * Regle metier 3 : La date de connexion est generee automatiquement
     */
    public function testDateConnexionAutoGenerated(): void
    {
        $this->assertInstanceOf(\DateTimeInterface::class, $this->historique->getDateConnexion());
    }

    /**
     * Regle metier 4 : Enregistrement d'une connexion echouee avec raison
     */
    public function testFailedConnectionWithReason(): void
    {
        $this->historique->setStatut('FAILED');
        $this->historique->setRaisonEchec('Mot de passe incorrect');

        $this->assertEquals('FAILED', $this->historique->getStatut());
        $this->assertEquals('Mot de passe incorrect', $this->historique->getRaisonEchec());
    }

    /**
     * Regle metier 5 : La raison d'echec est null pour les connexions reussies
     */
    public function testSuccessfulConnectionNoFailureReason(): void
    {
        $this->assertEquals('SUCCESS', $this->historique->getStatut());
        $this->assertNull($this->historique->getRaisonEchec());
    }

    /**
     * Regle metier 6 : Les informations device/browser sont optionnelles
     */
    public function testOptionalDeviceAndBrowserInfo(): void
    {
        $this->assertNull($this->historique->getDeviceInfo());
        $this->assertNull($this->historique->getBrowserInfo());
        $this->assertNull($this->historique->getIpAddress());
    }
}
