<?php

namespace App\Tests\Unit\Entity;

use App\Entity\Compte;
use App\Entity\TransactionBancaire;
use App\Enum\TransactionType;
use PHPUnit\Framework\TestCase;

class TransactionBancaireTest extends TestCase
{
    private TransactionBancaire $transaction;

    protected function setUp(): void
    {
        $this->transaction = new TransactionBancaire();
    }

    /**
     * Regle metier 1 : Creation complete d'une transaction (virement)
     */
    public function testTransactionCreationVirement(): void
    {
        $compteSource = new Compte();
        $compteSource->setNumeroCompte('UNI-SRC-001');

        $compteDest = new Compte();
        $compteDest->setNumeroCompte('UNI-DST-002');

        $this->transaction->setCompteSource($compteSource);
        $this->transaction->setCompteDestination($compteDest);
        $this->transaction->setType(TransactionType::VIREMENT);
        $this->transaction->setMontant('1500.00');
        $this->transaction->setDescription('Virement mensuel');

        $this->assertSame($compteSource, $this->transaction->getCompteSource());
        $this->assertSame($compteDest, $this->transaction->getCompteDestination());
        $this->assertSame(TransactionType::VIREMENT, $this->transaction->getType());
        $this->assertEquals('1500.00', $this->transaction->getMontant());
        $this->assertEquals('Virement mensuel', $this->transaction->getDescription());
    }

    /**
     * Regle metier 2 : La date de creation est generee automatiquement
     */
    public function testDateCreationAutoGenerated(): void
    {
        $this->assertInstanceOf(\DateTimeInterface::class, $this->transaction->getDateCreation());
    }

    /**
     * Regle metier 3 : Transaction de type RETRAIT (pas de compte destination)
     */
    public function testTransactionRetrait(): void
    {
        $compteSource = new Compte();
        $compteSource->setNumeroCompte('UNI-SRC-001');

        $this->transaction->setCompteSource($compteSource);
        $this->transaction->setType(TransactionType::RETRAIT);
        $this->transaction->setMontant('200.00');

        $this->assertSame(TransactionType::RETRAIT, $this->transaction->getType());
        $this->assertNull($this->transaction->getCompteDestination());
        $this->assertEquals('200.00', $this->transaction->getMontant());
    }

    /**
     * Regle metier 4 : Transaction de type DEPOT
     */
    public function testTransactionDepot(): void
    {
        $compteSource = new Compte();
        $compteSource->setNumeroCompte('UNI-SRC-001');

        $this->transaction->setCompteSource($compteSource);
        $this->transaction->setType(TransactionType::DEPOT);
        $this->transaction->setMontant('3000.00');

        $this->assertSame(TransactionType::DEPOT, $this->transaction->getType());
        $this->assertEquals('3000.00', $this->transaction->getMontant());
    }

    /**
     * Regle metier 5 : Les trois types de transaction existent
     */
    public function testAllTransactionTypes(): void
    {
        $this->transaction->setType(TransactionType::VIREMENT);
        $this->assertSame(TransactionType::VIREMENT, $this->transaction->getType());

        $this->transaction->setType(TransactionType::RETRAIT);
        $this->assertSame(TransactionType::RETRAIT, $this->transaction->getType());

        $this->transaction->setType(TransactionType::DEPOT);
        $this->assertSame(TransactionType::DEPOT, $this->transaction->getType());
    }

    /**
     * Regle metier 6 : La description est optionnelle
     */
    public function testDescriptionIsOptional(): void
    {
        $this->assertNull($this->transaction->getDescription());

        $this->transaction->setDescription('Paiement facture');
        $this->assertEquals('Paiement facture', $this->transaction->getDescription());
    }

    /**
     * Regle metier 7 : Le compte destination est nullable (pour retrait et depot)
     */
    public function testCompteDestinationNullable(): void
    {
        $this->assertNull($this->transaction->getCompteDestination());
    }

    /**
     * Regle metier 8 : Simulation d'un virement avec mise a jour des soldes
     */
    public function testVirementUpdatesSoldes(): void
    {
        $compteSource = new Compte();
        $compteSource->setSolde('5000.00');

        $compteDest = new Compte();
        $compteDest->setSolde('1000.00');

        $montant = 2000.00;

        $nouveauSoldeSource = number_format((float)$compteSource->getSolde() - $montant, 2, '.', '');
        $nouveauSoldeDest = number_format((float)$compteDest->getSolde() + $montant, 2, '.', '');

        $compteSource->setSolde($nouveauSoldeSource);
        $compteDest->setSolde($nouveauSoldeDest);

        $this->assertEquals('3000.00', $compteSource->getSolde());
        $this->assertEquals('3000.00', $compteDest->getSolde());
    }
}
