<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Credit extends \App\Entity\Credit implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'agent' => [parent::class, 'agent', null, 16],
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'dateDebutPaiement' => [parent::class, 'dateDebutPaiement', null, 16],
        "\0".parent::class."\0".'dateMaj' => [parent::class, 'dateMaj', null, 16],
        "\0".parent::class."\0".'datePrise' => [parent::class, 'datePrise', null, 16],
        "\0".parent::class."\0".'dateTraitement' => [parent::class, 'dateTraitement', null, 16],
        "\0".parent::class."\0".'dureeEnMois' => [parent::class, 'dureeEnMois', null, 16],
        "\0".parent::class."\0".'idCredit' => [parent::class, 'idCredit', null, 16],
        "\0".parent::class."\0".'mensualite' => [parent::class, 'mensualite', null, 16],
        "\0".parent::class."\0".'montant' => [parent::class, 'montant', null, 16],
        "\0".parent::class."\0".'montantTotal' => [parent::class, 'montantTotal', null, 16],
        "\0".parent::class."\0".'motifDemande' => [parent::class, 'motifDemande', null, 16],
        "\0".parent::class."\0".'motifRejet' => [parent::class, 'motifRejet', null, 16],
        "\0".parent::class."\0".'salaireMensuel' => [parent::class, 'salaireMensuel', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'tauxInteret' => [parent::class, 'tauxInteret', null, 16],
        "\0".parent::class."\0".'typeContrat' => [parent::class, 'typeContrat', null, 16],
        'agent' => [parent::class, 'agent', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'dateDebutPaiement' => [parent::class, 'dateDebutPaiement', null, 16],
        'dateMaj' => [parent::class, 'dateMaj', null, 16],
        'datePrise' => [parent::class, 'datePrise', null, 16],
        'dateTraitement' => [parent::class, 'dateTraitement', null, 16],
        'dureeEnMois' => [parent::class, 'dureeEnMois', null, 16],
        'idCredit' => [parent::class, 'idCredit', null, 16],
        'mensualite' => [parent::class, 'mensualite', null, 16],
        'montant' => [parent::class, 'montant', null, 16],
        'montantTotal' => [parent::class, 'montantTotal', null, 16],
        'motifDemande' => [parent::class, 'motifDemande', null, 16],
        'motifRejet' => [parent::class, 'motifRejet', null, 16],
        'salaireMensuel' => [parent::class, 'salaireMensuel', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'tauxInteret' => [parent::class, 'tauxInteret', null, 16],
        'typeContrat' => [parent::class, 'typeContrat', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
