<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contrat extends \App\Entity\Contrat implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'agent' => [parent::class, 'agent', null, 16],
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'credit' => [parent::class, 'credit', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'dateDebut' => [parent::class, 'dateDebut', null, 16],
        "\0".parent::class."\0".'dateFin' => [parent::class, 'dateFin', null, 16],
        "\0".parent::class."\0".'dateGeneration' => [parent::class, 'dateGeneration', null, 16],
        "\0".parent::class."\0".'dateMaj' => [parent::class, 'dateMaj', null, 16],
        "\0".parent::class."\0".'dateSignature' => [parent::class, 'dateSignature', null, 16],
        "\0".parent::class."\0".'dureeEnMois' => [parent::class, 'dureeEnMois', null, 16],
        "\0".parent::class."\0".'idContrat' => [parent::class, 'idContrat', null, 16],
        "\0".parent::class."\0".'mensualite' => [parent::class, 'mensualite', null, 16],
        "\0".parent::class."\0".'montantCredit' => [parent::class, 'montantCredit', null, 16],
        "\0".parent::class."\0".'montantTotal' => [parent::class, 'montantTotal', null, 16],
        "\0".parent::class."\0".'numeroContrat' => [parent::class, 'numeroContrat', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'tauxInteret' => [parent::class, 'tauxInteret', null, 16],
        'agent' => [parent::class, 'agent', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'credit' => [parent::class, 'credit', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'dateDebut' => [parent::class, 'dateDebut', null, 16],
        'dateFin' => [parent::class, 'dateFin', null, 16],
        'dateGeneration' => [parent::class, 'dateGeneration', null, 16],
        'dateMaj' => [parent::class, 'dateMaj', null, 16],
        'dateSignature' => [parent::class, 'dateSignature', null, 16],
        'dureeEnMois' => [parent::class, 'dureeEnMois', null, 16],
        'idContrat' => [parent::class, 'idContrat', null, 16],
        'mensualite' => [parent::class, 'mensualite', null, 16],
        'montantCredit' => [parent::class, 'montantCredit', null, 16],
        'montantTotal' => [parent::class, 'montantTotal', null, 16],
        'numeroContrat' => [parent::class, 'numeroContrat', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'tauxInteret' => [parent::class, 'tauxInteret', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
