<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'cartes' => [parent::class, 'cartes', null, 16],
        "\0".parent::class."\0".'cin' => [parent::class, 'cin', null, 16],
        "\0".parent::class."\0".'clientStatus' => [parent::class, 'clientStatus', null, 16],
        "\0".parent::class."\0".'comptes' => [parent::class, 'comptes', null, 16],
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'dateMaj' => [parent::class, 'dateMaj', null, 16],
        "\0".parent::class."\0".'dateNaissance' => [parent::class, 'dateNaissance', null, 16],
        "\0".parent::class."\0".'departement' => [parent::class, 'departement', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'estActif' => [parent::class, 'estActif', null, 16],
        "\0".parent::class."\0".'idUtilisateur' => [parent::class, 'idUtilisateur', null, 16],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null, 16],
        "\0".parent::class."\0".'matricule' => [parent::class, 'matricule', null, 16],
        "\0".parent::class."\0".'motDePasse' => [parent::class, 'motDePasse', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'reclamations' => [parent::class, 'reclamations', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'selectedOffer' => [parent::class, 'selectedOffer', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        "\0".parent::class."\0".'tokenExpiry' => [parent::class, 'tokenExpiry', null, 16],
        "\0".parent::class."\0".'verificationToken' => [parent::class, 'verificationToken', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'cartes' => [parent::class, 'cartes', null, 16],
        'cin' => [parent::class, 'cin', null, 16],
        'clientStatus' => [parent::class, 'clientStatus', null, 16],
        'comptes' => [parent::class, 'comptes', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'dateMaj' => [parent::class, 'dateMaj', null, 16],
        'dateNaissance' => [parent::class, 'dateNaissance', null, 16],
        'departement' => [parent::class, 'departement', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'estActif' => [parent::class, 'estActif', null, 16],
        'idUtilisateur' => [parent::class, 'idUtilisateur', null, 16],
        'isVerified' => [parent::class, 'isVerified', null, 16],
        'matricule' => [parent::class, 'matricule', null, 16],
        'motDePasse' => [parent::class, 'motDePasse', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'reclamations' => [parent::class, 'reclamations', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'selectedOffer' => [parent::class, 'selectedOffer', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
        'tokenExpiry' => [parent::class, 'tokenExpiry', null, 16],
        'verificationToken' => [parent::class, 'verificationToken', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
