<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Compte extends \App\Entity\Compte implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'estActif' => [parent::class, 'estActif', null, 16],
        "\0".parent::class."\0".'idCompte' => [parent::class, 'idCompte', null, 16],
        "\0".parent::class."\0".'numeroCompte' => [parent::class, 'numeroCompte', null, 16],
        "\0".parent::class."\0".'solde' => [parent::class, 'solde', null, 16],
        "\0".parent::class."\0".'transactionsEntrantes' => [parent::class, 'transactionsEntrantes', null, 16],
        "\0".parent::class."\0".'transactionsSortantes' => [parent::class, 'transactionsSortantes', null, 16],
        "\0".parent::class."\0".'typeCompte' => [parent::class, 'typeCompte', null, 16],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'estActif' => [parent::class, 'estActif', null, 16],
        'idCompte' => [parent::class, 'idCompte', null, 16],
        'numeroCompte' => [parent::class, 'numeroCompte', null, 16],
        'solde' => [parent::class, 'solde', null, 16],
        'transactionsEntrantes' => [parent::class, 'transactionsEntrantes', null, 16],
        'transactionsSortantes' => [parent::class, 'transactionsSortantes', null, 16],
        'typeCompte' => [parent::class, 'typeCompte', null, 16],
        'utilisateur' => [parent::class, 'utilisateur', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
