<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Session extends \App\Entity\Session implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateCreation' => [parent::class, 'dateCreation', null, 16],
        "\0".parent::class."\0".'dateExpiration' => [parent::class, 'dateExpiration', null, 16],
        "\0".parent::class."\0".'estActive' => [parent::class, 'estActive', null, 16],
        "\0".parent::class."\0".'idSession' => [parent::class, 'idSession', null, 16],
        "\0".parent::class."\0".'token' => [parent::class, 'token', null, 16],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null, 16],
        'dateCreation' => [parent::class, 'dateCreation', null, 16],
        'dateExpiration' => [parent::class, 'dateExpiration', null, 16],
        'estActive' => [parent::class, 'estActive', null, 16],
        'idSession' => [parent::class, 'idSession', null, 16],
        'token' => [parent::class, 'token', null, 16],
        'utilisateur' => [parent::class, 'utilisateur', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
