<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Carte extends \App\Entity\Carte implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'bank' => [parent::class, 'bank', null, 16],
        "\0".parent::class."\0".'cardNumber' => [parent::class, 'cardNumber', null, 16],
        "\0".parent::class."\0".'expirationDate' => [parent::class, 'expirationDate', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'solde' => [parent::class, 'solde', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'transactions' => [parent::class, 'transactions', null, 16],
        "\0".parent::class."\0".'typeCarte' => [parent::class, 'typeCarte', null, 16],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'bank' => [parent::class, 'bank', null, 16],
        'cardNumber' => [parent::class, 'cardNumber', null, 16],
        'expirationDate' => [parent::class, 'expirationDate', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'solde' => [parent::class, 'solde', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'transactions' => [parent::class, 'transactions', null, 16],
        'typeCarte' => [parent::class, 'typeCarte', null, 16],
        'utilisateur' => [parent::class, 'utilisateur', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
