<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HistoriqueConnexion extends \App\Entity\HistoriqueConnexion implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'browserInfo' => [parent::class, 'browserInfo', null, 16],
        "\0".parent::class."\0".'dateConnexion' => [parent::class, 'dateConnexion', null, 16],
        "\0".parent::class."\0".'deviceInfo' => [parent::class, 'deviceInfo', null, 16],
        "\0".parent::class."\0".'idHistorique' => [parent::class, 'idHistorique', null, 16],
        "\0".parent::class."\0".'ipAddress' => [parent::class, 'ipAddress', null, 16],
        "\0".parent::class."\0".'raisonEchec' => [parent::class, 'raisonEchec', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null, 16],
        'browserInfo' => [parent::class, 'browserInfo', null, 16],
        'dateConnexion' => [parent::class, 'dateConnexion', null, 16],
        'deviceInfo' => [parent::class, 'deviceInfo', null, 16],
        'idHistorique' => [parent::class, 'idHistorique', null, 16],
        'ipAddress' => [parent::class, 'ipAddress', null, 16],
        'raisonEchec' => [parent::class, 'raisonEchec', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'utilisateur' => [parent::class, 'utilisateur', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
