<?php

namespace ContainerNkBRGYp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K45EsEUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K45EsEU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K45EsEU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contratRepo' => ['privates', 'App\\Repository\\ContratRepository', 'getContratRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\CreditRepository', 'getCreditRepositoryService', true],
        ], [
            'contratRepo' => 'App\\Repository\\ContratRepository',
            'repo' => 'App\\Repository\\CreditRepository',
        ]);
    }
}
