<?php

namespace ContainerNkBRGYp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MNjJK3xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mNjJK3x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\TransactionBancaireRepository', 'getTransactionBancaireRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\TransactionBancaireRepository',
        ]);

        if (isset($container->privates['.service_locator.mNjJK3x'])) {
            return $container->privates['.service_locator.mNjJK3x'];
        }

        return $container->privates['.service_locator.mNjJK3x'] = $instance;
    }
}
