<?php

namespace ContainerNkBRGYp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9AQgEIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9A_qgEI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'em' => '?',
            'hasher' => '?',
        ]);

        if (isset($container->privates['.service_locator.9A_qgEI'])) {
            return $container->privates['.service_locator.9A_qgEI'];
        }

        return $container->privates['.service_locator.9A_qgEI'] = $instance;
    }
}
