parameters:
    # ton paramètre pour les réclamations
    reclamations_directory: '%kernel.project_dir%/public/uploads/reclamations'
    app.url: '%env(APP_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\HCaptchaService:
        arguments:
            $hcaptchaSecretKey: '%env(HCAPTCHA_SECRET_KEY)%'
            $hcaptchaSiteKey: '%env(HCAPTCHA_SITE_KEY)%'

    App\Service\EmailService:
        arguments:
            $mailFromAddress: '%env(MAIL_FROM_ADDRESS)%'
            $mailFromName: '%env(MAIL_FROM_NAME)%'

    App\Service\ContractBrevoService:
        arguments:
            $brevoApiKey: '%env(BREVO_API_KEY)%'
            $brevoSenderEmail: '%env(BREVO_FROM)%'
            $brevoSenderName: '%env(BREVO_FROM_NAME)%'

    App\Service\ChatbotService:
        arguments:
            $ollamaUrl: '%env(OLLAMA_URL)%'

    App\Service\NewsService:
        arguments:
            $gnewsApiKey: '%env(GNEWS_API_KEY)%'

    App\Service\GrokService:
        arguments:
            $groqApiKey: '%env(GROQ_API_KEY)%'

    App\Service\AIService:
        arguments:
            $huggingfaceToken: '%env(HUGGINGFACE_TOKEN)%'

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 10 }

    App\EventListener\BannedUserListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 20 }


    
    App\Service\NotificationService:
        arguments:
            $mailFromAddress: '%env(MAIL_FROM_ADDRESS)%'
            $mailFromName: '%env(MAIL_FROM_NAME)%'
            $appUrl: '%app.url%'
            
    App\Service\TwilioService:
        arguments:
            $sid: '%env(TWILIO_SID)%'
            $token: '%env(TWILIO_TOKEN)%'
            $from: '%env(TWILIO_FROM)%'
    
    App\Service\ImageModerationService:
        arguments:
            $ocrSpaceApiKey: '%env(OCR_SPACE_API_KEY)%'
            $logger: '@logger'

    App\Service\SentimentAnalysisService:
        arguments:
            $huggingFaceToken: '%env(HUGGINGFACE_TOKEN)%'
            $logger: '@logger'

    App\Service\AutoReplyService:
        class: App\Service\AutoReplyService
        arguments:
            $openRouterKey: '%env(OPENROUTER_API_KEY)%'
            $logger: '@logger'
    
    App\Service\DuplicateDetectionService:
        arguments:
            $edenAiKey: '%env(EDEN_AI_API_KEY)%'  # Laisser vide pour utiliser la version locale
            $logger: '@logger'
    # Service de résumé amélioré
    App\Service\TextSummarizer:
        arguments:
            $sentimentService: '@App\Service\SentimentAnalysisService'


     # Service ML
    App\Service\MLPredictionService:
        arguments:
            $httpClient: '@http_client'
            $logger: '@logger'
            $mlApiUrl: '%env(ML_API_URL)%'

    # Client HTTP
    Symfony\Contracts\HttpClient\HttpClientInterface:
        factory: ['Symfony\Component\HttpClient\HttpClient', 'create']
        arguments:
            $defaultOptions:
                timeout: 10
                max_redirects: 3