<?php

namespace ContainerNGx2ZEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VwrwUDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vwrwU_D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vwrwU_D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ContratRepository', 'getContratRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ContratRepository',
        ]);
    }
}
