<?php

namespace ContainerNGx2ZEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContractPdfGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ContractPdfGenerator' shared autowired service.
     *
     * @return \App\Service\ContractPdfGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ContractPdfGenerator.php';

        return $container->privates['App\\Service\\ContractPdfGenerator'] = new \App\Service\ContractPdfGenerator();
    }
}
