<?php

namespace ContainerNGx2ZEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EmailService' shared autowired service.
     *
     * @return \App\Service\EmailService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/EmailService.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/MailerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Mailer.php';

        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\Service\\EmailService'])) {
            return $container->privates['App\\Service\\EmailService'];
        }
        $b = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['App\\Service\\EmailService'])) {
            return $container->privates['App\\Service\\EmailService'];
        }
        $c = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Service\\EmailService'])) {
            return $container->privates['App\\Service\\EmailService'];
        }

        $instance = new \App\Service\EmailService(new \Symfony\Component\Mailer\Mailer($a, $b, $c), $container->getEnv('MAIL_FROM_ADDRESS'), $container->getEnv('MAIL_FROM_NAME'));

        if (isset($container->privates['App\\Service\\EmailService'])) {
            return $container->privates['App\\Service\\EmailService'];
        }

        return $container->privates['App\\Service\\EmailService'] = $instance;
    }
}
