<?php

namespace ContainerNGx2ZEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHCaptchaServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\HCaptchaService' shared autowired service.
     *
     * @return \App\Service\HCaptchaService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/HCaptchaService.php';

        return $container->privates['App\\Service\\HCaptchaService'] = new \App\Service\HCaptchaService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('HCAPTCHA_SECRET_KEY'), $container->getEnv('HCAPTCHA_SITE_KEY'));
    }
}
