<?php

namespace ContainerNGx2ZEJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginFormAuthenticatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\LoginFormAuthenticator' shared autowired service.
     *
     * @return \App\Security\LoginFormAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AbstractAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/InteractiveAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AbstractLoginFormAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/src/Security/LoginFormAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authentication/AuthenticationSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/LoginSuccessHandler.php';

        $a = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['App\\Security\\LoginFormAuthenticator'])) {
            return $container->privates['App\\Security\\LoginFormAuthenticator'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Security\\LoginFormAuthenticator'])) {
            return $container->privates['App\\Security\\LoginFormAuthenticator'];
        }
        $c = ($container->privates['App\\Service\\EmailService'] ?? $container->load('getEmailServiceService'));

        if (isset($container->privates['App\\Security\\LoginFormAuthenticator'])) {
            return $container->privates['App\\Security\\LoginFormAuthenticator'];
        }
        $d = ($container->services['router'] ?? self::getRouterService($container));

        $instance = new \App\Security\LoginFormAuthenticator($d, ($container->privates['App\\Service\\HCaptchaService'] ?? $container->load('getHCaptchaServiceService')), new \App\Security\LoginSuccessHandler($d, $a, $b, $c));

        if (isset($container->privates['App\\Security\\LoginFormAuthenticator'])) {
            return $container->privates['App\\Security\\LoginFormAuthenticator'];
        }

        return $container->privates['App\\Security\\LoginFormAuthenticator'] = $instance;
    }
}
